using System.Collections.Generic;

namespace Modules_Replacer
{
    public static class ModulesCollection
    {
        /// <summary>
        /// Словарь русских названий модулей.
        /// </summary>
        public static List<Station> StationNames { get; set; }
        /// <summary>
        /// Статический конструктор.
        /// </summary>
        static ModulesCollection()
        {
            StationNames = new List<Station>();
            StationNames.Add(new Station("struct_arg_base_01_macro", "Аргон Базовый коннектор 01"));
            StationNames.Add(new Station("struct_arg_base_02_macro", "Аргон Базовый коннектор 02"));
            StationNames.Add(new Station("struct_arg_base_03_macro", "Аргон Базовый коннектор 03"));
            StationNames.Add(new Station("struct_arg_vertical_01_macro", "Аргон Вертикальный коннектор 01"));
            StationNames.Add(new Station("struct_arg_vertical_02_macro", "Аргон Вертикальный коннектор 02"));
            StationNames.Add(new Station("struct_arg_cross_01_macro", "Аргон Крестовой коннектор 01"));
            StationNames.Add(new Station("struct_ter_base_01_macro", "Земляне Базовый коннектор 01"));
            StationNames.Add(new Station("struct_ter_base_02_macro", "Земляне Базовый коннектор 02"));
            StationNames.Add(new Station("struct_ter_base_03_macro", "Земляне Базовый коннектор 03"));
            StationNames.Add(new Station("struct_ter_vertical_01_macro", "Земляне Вертикальный коннектор 01"));
            StationNames.Add(new Station("struct_ter_vertical_02_macro", "Земляне Вертикальный коннектор 02"));
            StationNames.Add(new Station("struct_ter_cross_01_macro", "Земляне Крестовой коннектор 01"));
            StationNames.Add(new Station("struct_par_base_01_macro", "Паранид Базовый коннектор 01"));
            StationNames.Add(new Station("struct_par_base_02_macro", "Паранид Базовый коннектор 02"));
            StationNames.Add(new Station("struct_par_base_03_macro", "Паранид Базовый коннектор 03"));
            StationNames.Add(new Station("struct_par_vertical_01_macro", "Паранид Вертикальный коннектор 01"));
            StationNames.Add(new Station("struct_par_vertical_02_macro", "Паранид Вертикальный коннектор 02"));
            StationNames.Add(new Station("struct_par_cross_01_macro", "Сплит Крестовой коннектор 01"));
            StationNames.Add(new Station("struct_par_cross_02_macro", "Сплит Крестовой коннектор 02"));
            StationNames.Add(new Station("struct_par_cross_03_macro", "Сплит Крестовой коннектор 03"));
            StationNames.Add(new Station("struct_spl_base_01_macro", "Сплит Базовый коннектор 01"));
            StationNames.Add(new Station("struct_spl_base_02_macro", "Сплит Базовый коннектор 02"));
            StationNames.Add(new Station("struct_spl_base_03_macro", "Сплит Базовый коннектор 03"));
            StationNames.Add(new Station("struct_spl_vertical_01_macro", "Сплит Вертикальный коннектор 01"));
            StationNames.Add(new Station("struct_spl_vertical_02_macro", "Сплит Вертикальный коннектор 02"));
            StationNames.Add(new Station("struct_spl_cross_01_macro", "Сплит Крестовой коннектор 01"));
            StationNames.Add(new Station("struct_tel_base_01_macro", "Телади Базовый коннектор 01"));
            StationNames.Add(new Station("struct_tel_base_02_macro", "Телади Базовый коннектор 02"));
            StationNames.Add(new Station("struct_tel_base_03_macro", "Телади Базовый коннектор 03"));
            StationNames.Add(new Station("struct_tel_vertical_01_macro", "Телади Вертикальный коннектор 01"));
            StationNames.Add(new Station("struct_tel_vertical_02_macro", "Телади Вертикальный коннектор 02"));
            StationNames.Add(new Station("struct_tel_cross_01_macro", "Телади Крестовой коннектор 01"));
            StationNames.Add(new Station("buildmodule_gen_equip_l_macro", "Отсек обслуживания L-кораблей"));
            StationNames.Add(new Station("buildmodule_gen_equip_m_dockarea_01_macro", "Отсек обслуживания S/M-кораблей"));
            StationNames.Add(new Station("buildmodule_gen_equip_xl_macro", "Отсек обслуживания XL-кораблей"));
            StationNames.Add(new Station("buildmodule_gen_ships_l_macro", "Производственный отсек L-кораблей"));
            StationNames.Add(new Station("buildmodule_gen_ships_m_dockarea_01_macro", "Производственный отсек S/M-кораблей"));
            StationNames.Add(new Station("buildmodule_gen_ships_xl_macro", "Производственный отсек XL-кораблей"));
            StationNames.Add(new Station("buildmodule_ter_equip_l_macro", "ЗЕМ Отсек обслуживания L-кораблей"));
            StationNames.Add(new Station("buildmodule_ter_equip_m_dockarea_01_macro", "ЗЕМ Отсек обслуживания S/M-кораблей"));
            StationNames.Add(new Station("buildmodule_ter_equip_xl_macro", "ЗЕМ Отсек обслуживания XL-кораблей"));
            StationNames.Add(new Station("buildmodule_ter_ships_l_macro", "ЗЕМ Производственный отсек L-кораблей"));
            StationNames.Add(new Station("buildmodule_ter_ships_m_dockarea_01_macro", "ЗЕМ Производственный отсек S/M-кораблей"));
            StationNames.Add(new Station("buildmodule_ter_ships_xl_macro", "ЗЕМ Производственный отсек XL-кораблей"));
            StationNames.Add(new Station("storage_arg_s_liquid_01_macro", "Аргон S Хранилище жидкостей"));
            StationNames.Add(new Station("storage_arg_s_container_01_macro", "Аргон S Хранилище контейнеров"));
            StationNames.Add(new Station("storage_arg_s_solid_01_macro", "Аргон S Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_arg_m_liquid_01_macro", "Аргон M Хранилище жидкостей"));
            StationNames.Add(new Station("storage_arg_m_container_01_macro", "Аргон M Хранилище контейнеров"));
            StationNames.Add(new Station("storage_arg_m_solid_01_macro", "Аргон M Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_arg_l_liquid_01_macro", "Аргон L Хранилище жидкостей"));
            StationNames.Add(new Station("storage_arg_l_container_01_macro", "Аргон L Хранилище контейнеров"));
            StationNames.Add(new Station("storage_arg_l_solid_01_macro", "Аргон L Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_ter_s_liquid_01_macro", "Земляне S Хранилище жидкостей"));
            StationNames.Add(new Station("storage_ter_s_container_01_macro", "Земляне S Хранилище контейнеров"));
            StationNames.Add(new Station("storage_ter_s_solid_01_macro", "Земляне S Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_ter_m_liquid_01_macro", "Земляне M Хранилище жидкостей"));
            StationNames.Add(new Station("storage_ter_m_container_01_macro", "Земляне M Хранилище контейнеров"));
            StationNames.Add(new Station("storage_ter_m_solid_01_macro", "Земляне M Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_ter_l_liquid_01_macro", "Земляне L Хранилище жидкостей"));
            StationNames.Add(new Station("storage_ter_l_container_01_macro", "Земляне L Хранилище контейнеров"));
            StationNames.Add(new Station("storage_ter_l_solid_01_macro", "Земляне L Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_par_s_liquid_01_macro", "Паранид S Хранилище жидкостей"));
            StationNames.Add(new Station("storage_par_s_container_01_macro", "Паранид S Хранилище контейнеров"));
            StationNames.Add(new Station("storage_par_s_solid_01_macro", "Паранид S Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_par_m_liquid_01_macro", "Паранид M Хранилище жидкостей"));
            StationNames.Add(new Station("storage_par_m_container_01_macro", "Паранид M Хранилище контейнеров"));
            StationNames.Add(new Station("storage_par_m_solid_01_macro", "Паранид M Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_par_l_liquid_01_macro", "Паранид L Хранилище жидкостей"));
            StationNames.Add(new Station("storage_par_l_container_01_macro", "Паранид L Хранилище контейнеров"));
            StationNames.Add(new Station("storage_par_l_solid_01_macro", "Паранид L Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_spl_s_liquid_01_macro", "Сплит S Хранилище жидкостей"));
            StationNames.Add(new Station("storage_spl_s_container_01_macro", "Сплит S Хранилище контейнеров"));
            StationNames.Add(new Station("storage_spl_s_solid_01_macro", "Сплит S Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_spl_m_liquid_01_macro", "Сплит M Хранилище жидкостей"));
            StationNames.Add(new Station("storage_spl_m_container_01_macro", "Сплит M Хранилище контейнеров"));
            StationNames.Add(new Station("storage_spl_m_solid_01_macro", "Сплит M Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_spl_l_liquid_01_macro", "Сплит L Хранилище жидкостей"));
            StationNames.Add(new Station("storage_spl_l_container_01_macro", "Сплит L Хранилище контейнеров"));
            StationNames.Add(new Station("storage_spl_l_solid_01_macro", "Сплит L Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_tel_s_liquid_01_macro", "Телади S Хранилище жидкостей"));
            StationNames.Add(new Station("storage_tel_s_container_01_macro", "Телади S Хранилище контейнеров"));
            StationNames.Add(new Station("storage_tel_s_solid_01_macro", "Телади S Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_tel_m_liquid_01_macro", "Телади M Хранилище жидкостей"));
            StationNames.Add(new Station("storage_tel_m_container_01_macro", "Телади M Хранилище контейнеров"));
            StationNames.Add(new Station("storage_tel_m_solid_01_macro", "Телади M Хранилище твёрдых грузов"));
            StationNames.Add(new Station("storage_tel_l_liquid_01_macro", "Телади L Хранилище жидкостей"));
            StationNames.Add(new Station("storage_tel_l_container_01_macro", "Телади L Хранилище контейнеров"));
            StationNames.Add(new Station("storage_tel_l_solid_01_macro", "Телади L Хранилище твёрдых грузов"));
            StationNames.Add(new Station("hab_arg_s_01_macro", "Аргон S Ареал"));
            StationNames.Add(new Station("hab_arg_m_01_macro", "Аргон M Ареал"));
            StationNames.Add(new Station("hab_arg_l_01_macro", "Аргон L Ареал"));
            StationNames.Add(new Station("hab_ter_s_01_macro", "Земляне S Жилые помещения"));
            StationNames.Add(new Station("hab_ter_m_01_macro", "Земляне M Жилые помещения"));
            StationNames.Add(new Station("hab_ter_l_01_macro", "Земляне L Жилые помещения"));
            StationNames.Add(new Station("hab_par_s_01_macro", "Паранид S Купол"));
            StationNames.Add(new Station("hab_par_m_01_macro", "Паранид M Купол"));
            StationNames.Add(new Station("hab_par_l_01_macro", "Паранид L Купол"));
            StationNames.Add(new Station("hab_spl_s_01_macro", "Сплит S Зал"));
            StationNames.Add(new Station("hab_spl_m_01_macro", "Сплит M Зал"));
            StationNames.Add(new Station("hab_spl_l_01_macro", "Сплит L Зал"));
            StationNames.Add(new Station("hab_tel_s_01_macro", "Телади S Биом"));
            StationNames.Add(new Station("hab_tel_m_01_macro", "Телади M Биом"));
            StationNames.Add(new Station("hab_tel_l_01_macro", "Телади L Биом"));
            StationNames.Add(new Station("dockarea_arg_m_station_01_lowtech_macro", "1M6S Базовый Посадочная площадка"));
            StationNames.Add(new Station("dockarea_arg_m_station_01_hightech_macro", "1M6S Люкс Посадочная площадка"));
            StationNames.Add(new Station("dockarea_arg_m_station_01_macro", "1M6S Стандарт Посадочная площадка"));
            StationNames.Add(new Station("dockarea_arg_m_station_02_lowtech_macro", "3M6S Базовый Посадочная площадка"));
            StationNames.Add(new Station("dockarea_arg_m_station_02_hightech_macro", "3M6S Люкс Посадочная площадка"));
            StationNames.Add(new Station("dockarea_arg_m_station_02_macro", "3M6S Стандарт Посадочная площадка"));
            StationNames.Add(new Station("dockarea_arg_m_02_tradestation_01_macro", "8M Стандарт Посадочная площадка"));
            StationNames.Add(new Station("dockarea_ter_m_station_01_hightech_macro", "4M10S Люкс Посадочная площадка"));
            StationNames.Add(new Station("pier_arg_harbor_01_macro", "Аргон 3-Док Т Причал"));
            StationNames.Add(new Station("pier_arg_harbor_02_macro", "Аргон 1-Док Причал"));
            StationNames.Add(new Station("pier_arg_harbor_03_macro", "Аргон 3-Док Е Причал"));
            StationNames.Add(new Station("pier_ter_harbor_01_macro", "Земляне 3-Док Т Причал"));
            StationNames.Add(new Station("pier_ter_harbor_02_macro", "Земляне 1-Док Причал"));
            StationNames.Add(new Station("pier_ter_harbor_03_macro", "Земляне 3-Док Е Причал"));
            StationNames.Add(new Station("pier_ter_harbor_04_macro", "Земляне 4-Док Т Причал"));
            StationNames.Add(new Station("pier_ter_tradestation_01_macro", "Зем. Торговая станция Гекса-док Причал"));
            StationNames.Add(new Station("pier_par_harbor_01_macro", "Паранид 3-Док Т Причал"));
            StationNames.Add(new Station("pier_par_harbor_02_macro", "Паранид 1-Док Причал"));
            StationNames.Add(new Station("pier_par_harbor_03_macro", "Паранид 3-Док Е Причал"));
            StationNames.Add(new Station("pier_spl_harbor_01_macro", "Сплит 4-Док Т Причал"));
            StationNames.Add(new Station("pier_spl_harbor_02_macro", "Сплит 1-Док Причал"));
            StationNames.Add(new Station("pier_spl_harbor_03_macro", "Сплит 3-Док Е Причал"));
            StationNames.Add(new Station("pier_tel_harbor_01_macro", "Телади 3-Док Т Причал"));
            StationNames.Add(new Station("pier_tel_harbor_02_macro", "Телади 1-Док Причал"));
            StationNames.Add(new Station("pier_tel_harbor_03_macro", "Телади 3-Док Е Причал"));
            StationNames.Add(new Station("defence_arg_claim_01_macro", "Аргон Административный центр"));
            StationNames.Add(new Station("defence_ter_claim_01_macro", "Земляне Административный центр"));
            StationNames.Add(new Station("defence_par_claim_01_macro", "Паранид Административный центр"));
            StationNames.Add(new Station("defence_par_claim_story_01_macro", "Паранид Столица фракции"));
            StationNames.Add(new Station("defence_spl_claim_01_macro", "Сплит Административный центр"));
            StationNames.Add(new Station("defence_tel_claim_01_macro", "Телади Административный центр"));
            StationNames.Add(new Station("defence_arg_disc_01_macro", "Аргон Дисковая защитная платформа"));
            StationNames.Add(new Station("defence_arg_tube_01_macro", "Аргон Мостовая защитная платформа"));
            StationNames.Add(new Station("defence_ter_disc_01_macro", "Земляне Дисковая защитная платформа"));
            StationNames.Add(new Station("defence_ter_tube_01_macro", "Земляне Мостовая защитная платформа"));
            StationNames.Add(new Station("defence_par_disc_01_macro", "Паранид Дисковая защитная платформа"));
            StationNames.Add(new Station("defence_par_tube_01_macro", "Паранид Мостовая защитная платформа"));
            StationNames.Add(new Station("defence_spl_disc_01_macro", "Сплит Дисковая защитная платформа"));
            StationNames.Add(new Station("defence_spl_tube_01_macro", "Сплит Мостовая защитная платформа"));
            StationNames.Add(new Station("defence_tel_disc_01_macro", "Телади Дисковая защитная платформа"));
            StationNames.Add(new Station("defence_tel_tube_01_macro", "Телади Мостовая защитная платформа"));
            StationNames.Add(new Station("prod_gen_energycells_macro", "Производство энергоэлементов"));
            StationNames.Add(new Station("prod_ter_energycells_macro", "Земляне Производство энергоэлементов"));
            StationNames.Add(new Station("prod_gen_antimattercells_macro", "Производство АМ-элементов"));
            StationNames.Add(new Station("prod_gen_graphene_macro", "Производство графена"));
            StationNames.Add(new Station("prod_gen_siliconwafers_macro", "Производство кремниевых пластин"));
            StationNames.Add(new Station("prod_gen_refinedmetals_macro", "Производство очищенных металлов"));
            StationNames.Add(new Station("prod_gen_superfluidcoolant_macro", "Производство сверхтекучего хладагента"));
            StationNames.Add(new Station("prod_tel_teladianium_macro", "Производство теладиания"));
            StationNames.Add(new Station("prod_gen_water_macro", "Производство воды"));
            StationNames.Add(new Station("prod_gen_engineparts_macro", "Производство деталей двигателей"));
            StationNames.Add(new Station("prod_tel_engineparts_macro", "Телади Производство деталей двигателей"));
            StationNames.Add(new Station("prod_gen_hullparts_macro", "Производство деталей корпуса"));
            StationNames.Add(new Station("prod_tel_hullparts_macro", "Телади Производство деталей корпуса"));
            StationNames.Add(new Station("prod_ter_siliconcarbide_macro", "Производство карборунда"));
            StationNames.Add(new Station("prod_gen_quantumtubes_macro", "Производство квантовых трубок"));
            StationNames.Add(new Station("prod_ter_computronicsubstrate_macro", "Производство компьютронного субстрата"));
            StationNames.Add(new Station("prod_ter_metallicmicrolattice_macro", "Производство металлической микрорешётки"));
            StationNames.Add(new Station("prod_gen_microchips_macro", "Производство микросхем"));
            StationNames.Add(new Station("prod_gen_plasmaconductors_macro", "Производство плазмопроводов"));
            StationNames.Add(new Station("prod_gen_scanningarrays_macro", "Производство сканирующих матриц"));
            StationNames.Add(new Station("prod_tel_scanningarrays_macro", "Телади Производство сканирующих матриц"));
            StationNames.Add(new Station("prod_gen_advancedcomposites_macro", "Производство суперкомпозитов"));
            StationNames.Add(new Station("prod_tel_advancedcomposites_macro", "Телади Производство суперкомпозитов"));
            StationNames.Add(new Station("prod_gen_antimatterconverters_macro", "Производство АМ-конвертеров"));
            StationNames.Add(new Station("prod_gen_claytronics_macro", "Производство клэйтроники"));
            StationNames.Add(new Station("prod_gen_dronecomponents_macro", "Производство компонентов дронов"));
            StationNames.Add(new Station("prod_gen_weaponcomponents_macro", "Производство компонентов орудий"));
            StationNames.Add(new Station("prod_gen_missilecomponents_macro", "Производство ракет"));
            StationNames.Add(new Station("prod_gen_turretcomponents_macro", "Производство турелей"));
            StationNames.Add(new Station("prod_gen_shieldcomponents_macro", "Производство щитов"));
            StationNames.Add(new Station("prod_gen_fieldcoils_macro", "Производство полевых катушек"));
            StationNames.Add(new Station("prod_gen_advancedelectronics_macro", "Производство систем упреждения"));
            StationNames.Add(new Station("prod_gen_smartchips_macro", "Производство смарт-чипов"));
            StationNames.Add(new Station("prod_tel_swampplant_macro", "Производство болотной травы"));
            StationNames.Add(new Station("prod_arg_meat_macro", "Производство мяса"));
            StationNames.Add(new Station("prod_spl_cheltmeat_macro", "Производство челтов"));
            StationNames.Add(new Station("prod_tel_sunriseflowers_macro", "Производство подсолнечников"));
            StationNames.Add(new Station("prod_ter_proteinpaste_macro", "Производство протеиновой пасты"));
            StationNames.Add(new Station("prod_arg_wheat_macro", "Производство пшеницы"));
            StationNames.Add(new Station("prod_par_sojabeans_macro", "Производство соевых бобов"));
            StationNames.Add(new Station("prod_gen_spices_macro", "Производство специй"));
            StationNames.Add(new Station("prod_par_majasnails_macro", "Производство улиток майя"));
            StationNames.Add(new Station("prod_spl_scruffinfruit_macro", "Производство скруффинов"));
            StationNames.Add(new Station("prod_ter_mre_macro", "Производство земных пайков"));
            StationNames.Add(new Station("prod_tel_nostropoil_macro", "Производство ностропового масла"));
            StationNames.Add(new Station("prod_arg_foodrations_macro", "Производство рационов питания"));
            StationNames.Add(new Station("prod_par_sojahusk_macro", "Производство соевой пасты"));
            StationNames.Add(new Station("prod_tel_spaceweed_macro", "Производство космотабака"));
            StationNames.Add(new Station("prod_arg_spacefuel_macro", "Производство комотоплива"));
            StationNames.Add(new Station("prod_arg_medicalsupplies_macro", "Аргон Производство медикаментов"));
            StationNames.Add(new Station("prod_ter_medicalsupplies_macro", "Земляне Производство медикаментов"));
            StationNames.Add(new Station("prod_par_medicalsupplies_macro", "Паранид Производство медикаментов"));
            StationNames.Add(new Station("prod_spl_medicalsupplies_macro", "Сплит Производство медикаментов"));
            StationNames.Add(new Station("prod_tel_medicalsupplies_macro", "Телади Производство медикаментов"));
            StationNames.Add(new Station("prod_par_majadust_macro", "Производство порошка майя"));
            StationNames.Add(new Station("prod_ter_stimulants_macro", "Производство стимуляторов"));
            StationNames.Add(new Station("landmarks_player_hq_01_research_macro", "Штаб-квартира"));
            StationNames.Add(new Station("storage_pir_s_condensate_01_macro", "Сооружения для хранения конденсата"));
            StationNames.Add(new Station("storage_pir_l_condensate_01_macro", "Протектион генератор щитов"));
            StationNames.Add(new Station("welfare_gen_casino_01_macro", "Казино"));
            StationNames.Add(new Station("welfare_gen_gamblinghall_01_macro", "Игорный притон"));
            StationNames.Add(new Station("proc_gen_scrapworks_macro", "Обработчик металлолома"));
            StationNames.Add(new Station("prod_ter_scrap_recycler_macro", "Земляне Переработчик металлолома"));
            StationNames.Add(new Station("prod_gen_scrap_recycler_macro", "Переработчик металлолома"));
            StationNames.Add(new Station("struct_gen_venturerbase_01_macro", "Венчурный базовый коннектор 01"));
            StationNames.Add(new Station("struct_gen_venturerbase_02_macro", "Венчурный базовый коннектор 02"));
            StationNames.Add(new Station("struct_gen_venturerbase_03_macro", "Венчурный базовый коннектор 03"));
            StationNames.Add(new Station("struct_gen_venturervertical_01_macro", "Венчурный вертикальный коннектор 01"));
            StationNames.Add(new Station("struct_gen_venturervertical_02_macro", "Венчурный вертикальный коннектор 02"));
            StationNames.Add(new Station("struct_gen_venturercross_01_macro", "Венчурный крестовой коннектор 01"));
            int step = 6_777_215 / StationNames.Count;
            for (int i = 0; i < StationNames.Count; i++)
            {
                StationNames[i].SetForeground(10_000_000 + i * step);
            }
        }
    }
}
